FROM ubuntu:22.04

COPY poseidon-circuit /app/poseidon-circuit
ENV PATH="/app:${PATH}"
ENV RUSTFLAGS="-Ctarget-feature=+aes,+sha"

CMD ["sh", "-c", "/app/poseidon-circuit -j '{}'"]

# cp ../target/release/poseidon-circuit .
# docker build -t poseidon .
# docker run -it --rm poseidon